### ISSUE TITLE
how to get inpainted image

### ISSUE THREAD

**Issue by Lucifer504** [chandrasekaraditya/ReMOVE#1]
Excellent work, I wonder how can I get the inpainted image? It seems that I can only get a remove score here.

**Comment by chandrasekaraditya** [comment]
Hi @Lucifer504, thanks for your interest in our work! 

The ReMOVE score is a reference-free method to assess object erasure quality, it requires an inpainted image as input. You can use any editing model that can perform erasure (or a commercial inpainting tool) to get the inpainted image. For example, we use methods such as Stable-Diffusion Inpaint, Blended Latent Diffusion, GLIDE and Instruct-Pix2Pix in our full-text [here](https://arxiv.org/abs/2409.00707). Hope this helps!
